<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MunicipalServicesMVC.Domain\MunicipalServicesMVC.Domain.csproj" />
    <ProjectReference Include="..\MunicipalServicesMVC.Infrastructure\MunicipalServicesMVC.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
